/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import Objetos.Tiempo;
import Objetos.Juego;

/**
 *
 * @author yangel
 */
public class Menu_in extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form Menu_in
     */
    public Menu_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nuevo = new javax.swing.JButton();
        seg = new javax.swing.JLabel();
        Cargar = new javax.swing.JButton();
        Instrucciones = new javax.swing.JButton();
        Credit = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nuevo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Nuevo.setText("Juego nuevo");
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        getContentPane().add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        seg.setFont(new java.awt.Font("Yu Gothic", 1, 48)); // NOI18N
        seg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        seg.setText("Pikachu");
        seg.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        seg.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(seg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 501, -1));

        Cargar.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Cargar.setText("Cargar juego");
        Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CargarActionPerformed(evt);
            }
        });
        getContentPane().add(Cargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, -1, -1));

        Instrucciones.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Instrucciones.setText(" ¿Cómo jugarlo?");
        getContentPane().add(Instrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        Credit.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Credit.setText("Créditos");
        getContentPane().add(Credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        Juego juego = new Juego();
        juego.first_time();
        
        
        Menu_prin ventana = new Menu_prin();
        
        
        this.setVisible(false);
        ventana.setVisible(true);
        
            
            
        
        
        
    }//GEN-LAST:event_NuevoActionPerformed

    private void CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CargarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_in().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cargar;
    private javax.swing.JButton Credit;
    private javax.swing.JButton Instrucciones;
    private javax.swing.JButton Nuevo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel seg;
    // End of variables declaration//GEN-END:variables
}
